name: Flutter Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Configura o Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      # Instalar dependências com Flutter
      - name: Install dependencies
        run: flutter pub get

      # Verificar o formato do código (opcional)
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      # Analisar o código
      - name: Analyze project source
        run: flutter analyze
